version: "3.9"
services:
  app:
    container_name: gameserver
    build:
      context: .
    ports:
      - 8080:8080/tcp # Game server
      - 9000:9000/tcp # Health checks
    networks:
      - backend

networks:
  backend:
